package com.devcli.service;

import com.devcli.model.Commit;
import com.devcli.model.PullRequest;
import com.devcli.model.Repository;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;

public class ReportExporter {

    public static String exportWrappedHtml(String username, int totalCommits, String topLang, String topRepo, int streak, int techCount, int shippedCount, int prsCount) {
        String html = """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <title>DevShell 2026 Wrapped - @%s</title>
                    <style>
                        body { background: #0f172a; color: #f8fafc; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; }
                        .card { background: #1e293b; border-radius: 12px; padding: 30px; max-width: 600px; margin: 0 auto; box-shadow: 0 10px 30px rgba(0,0,0,0.5); border: 1px solid #334155; }
                        h1 { color: #38bdf8; text-align: center; font-size: 28px; }
                        .stat-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 30px; }
                        .stat-box { background: #0f172a; padding: 15px; border-radius: 8px; border-left: 4px solid #38bdf8; }
                        .stat-title { color: #94a3b8; font-size: 12px; text-transform: uppercase; }
                        .stat-value { font-size: 24px; font-weight: bold; margin-top: 5px; color: #f8fafc; }
                        .footer { text-align: center; margin-top: 30px; color: #64748b; font-size: 13px; }
                    </style>
                </head>
                <body>
                    <div class="card">
                        <h1>🚀 2026 DEVELOPER WRAPPED</h1>
                        <p style="text-align:center; color:#94a3b8;">Developer Summary for @%s</p>
                        <div class="stat-grid">
                            <div class="stat-box"><div class="stat-title">Total Commits</div><div class="stat-value">%d</div></div>
                            <div class="stat-box"><div class="stat-title">Top Language</div><div class="stat-value">%s</div></div>
                            <div class="stat-box"><div class="stat-title">Most Active Project</div><div class="stat-value">%s</div></div>
                            <div class="stat-box"><div class="stat-title">Longest Streak</div><div class="stat-value">%d Days</div></div>
                            <div class="stat-box"><div class="stat-title">Technologies Explored</div><div class="stat-value">%d</div></div>
                            <div class="stat-box"><div class="stat-title">Projects Shipped</div><div class="stat-value">%d</div></div>
                        </div>
                        <div class="footer">Generated by DevShell Personal Developer OS • Powered by SWYNX</div>
                    </div>
                </body>
                </html>
                """.formatted(username, username, totalCommits, topLang, topRepo, streak, techCount, shippedCount);

        try {
            File downloadsDir = new File(System.getProperty("user.home"), "Downloads");
            if (!downloadsDir.exists()) downloadsDir.mkdirs();
            Path file = new File(downloadsDir, "devshell-wrapped.html").toPath();
            Files.writeString(file, html);
            return file.toAbsolutePath().toString();
        } catch (Exception e) {
            return "devshell-wrapped.html";
        }
    }

    public static String exportPortfolioHtml(String username, int projectsCount, int reposCount, int commitsCount, int prsCount, int osCount, Map<String, Double> languages) {
        StringBuilder langList = new StringBuilder();
        if (languages != null) {
            languages.keySet().stream().limit(5).forEach(l -> langList.append("<li>").append(l).append("</li>"));
        }

        String html = """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <title>Developer Portfolio - @%s</title>
                    <style>
                        body { background: #090d16; color: #f8fafc; font-family: sans-serif; padding: 40px; }
                        .container { max-width: 800px; margin: 0 auto; background: #111827; padding: 40px; border-radius: 12px; border: 1px solid #1f2937; }
                        h1 { color: #60a5fa; margin-bottom: 5px; }
                        .badge-grid { display: flex; gap: 15px; margin: 25px 0; flex-wrap: wrap; }
                        .badge { background: #1e293b; padding: 12px 20px; border-radius: 8px; font-weight: bold; border: 1px solid #334155; }
                        .badge span { color: #60a5fa; display: block; font-size: 20px; }
                        ul { background: #1e293b; padding: 20px 40px; border-radius: 8px; line-height: 1.8; }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <h1>@%s</h1>
                        <p style="color:#94a3b8;">Personal Developer Portfolio</p>
                        <div class="badge-grid">
                            <div class="badge"><span>%d</span> Projects</div>
                            <div class="badge"><span>%d</span> Repositories</div>
                            <div class="badge"><span>%d</span> Commits</div>
                            <div class="badge"><span>%d</span> Pull Requests</div>
                            <div class="badge"><span>%d</span> Open Source</div>
                        </div>
                        <h2>PRIMARY STACK</h2>
                        <ul>
                            %s
                        </ul>
                    </div>
                </body>
                </html>
                """.formatted(username, username, projectsCount, reposCount, commitsCount, prsCount, osCount, langList.toString());

        try {
            File downloadsDir = new File(System.getProperty("user.home"), "Downloads");
            if (!downloadsDir.exists()) downloadsDir.mkdirs();
            Path file = new File(downloadsDir, "devshell-portfolio.html").toPath();
            Files.writeString(file, html);
            return file.toAbsolutePath().toString();
        } catch (Exception e) {
            return "devshell-portfolio.html";
        }
    }
}
